---
# file: site.yml

- name: Configure mjanja.co.ke
  hosts: web
  sudo: yes
  roles:
    - common
    - mariadb 
    - nginx
    - php5-fpm
#    - wordpress
    - munin
  vars_files:
    - "vars/{{ ansible_os_family }}.yml"

# vim: set sw=2 ts=2:
