---
# file: web.yml

- name: Configure web servers
  hosts: web
  user: ubuntu
  sudo: yes
  roles:
    - common
    - mariadb 
    - nginx
    - php5-fpm
    - munin
  vars_files:
    - vars/ipsets.yml
    - "vars/{{ ansible_os_family }}.yml"

# vim: set sw=2 ts=2:
