---
# file: roles/common/handlers/main.yml

- name: restart iptables
  service: name=iptables state=restarted

- name: restart iptables-persistent
  service: name=iptables-persistent state=restarted

- name: restart sshd
  service: name={{ sshd_service_name }} state=restarted

- name: reload sysctl
  command: sysctl -p /etc/sysctl.conf
