---
# create user or update settings if the user already exists
- name: Set password, shell, etc for provisioning user
  user: { name: '{{ provisioning_user.name }}', password: '{{ provisioning_user.password }}', shell: '{{ provisioning_user.shell }}', state: '{{ provisioning_user.state }}', createhome: 'yes' }

# vim: set ts=2 sw=2:
